name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        TF_VAR_github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        terraform validate
        terraform plan -no-color -out tfplan
        PLAN=$(terraform show -json tfplan)
        bash -e .github/tests/test/tests.sh "$PLAN" .github/tests/test/test_cases.txt
